# Generated by Django 5.2.3 on 2025-08-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('telephone_number', models.CharField(max_length=25)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact_person', models.CharField(max_length=150)),
                ('remarks', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
