# Generated by Django 5.2.3 on 2025-07-13 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DosageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('GG', 'General Goods'), ('MEDICINE', 'Medicince')], default='MEDICINE', max_length=10)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=250)),
                ('dosage', models.IntegerField()),
                ('prescription', models.TextField()),
                ('usage', models.TextField()),
                ('side_effects', models.TextField()),
                ('type', models.CharField(choices=[('OTC', 'Over-the-counter'), ('PRESCRIPTION', 'Prescription Drugs')], default='PRESCRIPTION', max_length=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('dosage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.dosageunit')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.medicineform')),
                ('product', models.OneToOneField(limit_choices_to={'category': 'MEDICINE'}, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(limit_choices_to={'category': 'GG'}, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
