# Generated by Django 5.2.3 on 2025-07-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='dosage_unit',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=150),
        ),
    ]
