# Generated by Django 5.2.3 on 2025-07-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_medicine_dosage_unit_alter_medicine_dosage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='type',
            new_name='prescription_type',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='prescription',
        ),
    ]
