# Generated by Django 5.2.3 on 2025-07-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_type_medicine_prescription_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='pampers', max_length=150),
            preserve_default=False,
        ),
    ]
