# Generated by Django 5.2.3 on 2025-07-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_brand_name_product_brand_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalgood',
            name='name',
        ),
        migrations.AddField(
            model_name='generalgood',
            name='type',
            field=models.CharField(default='TOILETRIES', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalgood',
            name='unit',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
